default_language_version:
    python: python3.12
repos:
  - repo: https://github.com/jazzband/pip-tools
    rev: 7.4.1
    hooks:
      - id: pip-compile
        name: pip-compile requirements-development.in
        files: requirements-(base|development).in
        args: [requirements/source/requirements-development.in, "--output-file", requirements/generated/requirements-development.txt, "--no-annotate"]
      - id: pip-compile
        name: pip-compile requirements-linting.in
        files: requirements-(base|linting).in
        args: [requirements/source/requirements-linting.in, "--output-file", requirements/generated/requirements-linting.txt, "--no-annotate"]
      - id: pip-compile
        name: pip-compile requirements-testing.in
        files: requirements-(base|testing).in
        args: [requirements/source/requirements-testing.in, "--output-file", requirements/generated/requirements-testing.txt, "--no-annotate"]
      - id: pip-compile
        name: pip-compile requirements-production.in
        files: requirements-(base|production).in
        args: [requirements/source/requirements-production.in, "--output-file", requirements/generated/requirements-production.txt, "--no-annotate"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.3
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format